from django.db import models

# Create your models here.

class MainInfo(models.Model):
    hpid = models.CharField(primary_key=True, max_length=20)
    name = models.CharField(max_length=200, default='')
    region = models.CharField(max_length=20, default='')
    div = models.CharField(max_length=300, default='')
    subject = models.CharField(max_length=1000, default='')
    tel = models.CharField(max_length=70, default='')
    etel = models.CharField(max_length=70, default='')
    info = models.CharField(max_length=500, default='')
    lat = models.FloatField(default=0)
    lon = models.FloatField(default=0)
    addr = models.CharField(max_length=500, default='')

class SpecialInfo(models.Model):
    hpid = models.ForeignKey(MainInfo, on_delete=models.CASCADE)
    emergency = models.CharField(max_length=4, default='')
    limbs = models.CharField(max_length=4, default='')
    pregnent = models.CharField(max_length=4, default='')
    newborn = models.CharField(max_length=4, default='')
    burn = models.CharField(max_length=4, default='')
    dialysis = models.CharField(max_length=4, default='')

class SubInfo(models.Model):
    hpid = models.ForeignKey(MainInfo, on_delete=models.CASCADE)
    mondayStart = models.CharField(max_length=10, default='')
    mondayEnd = models.CharField(max_length=10, default='')
    tuesdayStart = models.CharField(max_length=10, default='')
    tuesdayEnd = models.CharField(max_length=10, default='')
    wednesdayStart = models.CharField(max_length=10, default='')
    wednesdayEnd = models.CharField(max_length=10, default='')
    thursdayStart = models.CharField(max_length=10, default='')
    thursdayEnd = models.CharField(max_length=10, default='')
    fridayStart = models.CharField(max_length=10, default='')
    fridayEnd = models.CharField(max_length=10, default='')
    saturdayStart = models.CharField(max_length=10, default='')
    saturdayEnd = models.CharField(max_length=10, default='')
    sundayStart = models.CharField(max_length=10, default='')
    sundayEnd = models.CharField(max_length=10, default='')
    holidayStart = models.CharField(max_length=10, default='')
    holidayEnd = models.CharField(max_length=10, default='')

class GradeInfo(models.Model):
    hpid = models.ForeignKey(MainInfo, on_delete=models.CASCADE, default='')
    hurl = models.CharField(max_length=200, default='')
    highblood = models.IntegerField(default=0)
    lungCa = models.IntegerField(default=0)
    stomachCa = models.IntegerField(default=0)
    liverCa = models.IntegerField(default=0)
    bowelCa = models.IntegerField(default=0)
    breastCa = models.IntegerField(default=0)
    cesarean = models.IntegerField(default=0)
    antibiotics = models.IntegerField(default=0)
    injection = models.IntegerField(default=0)
    diabetes = models.IntegerField(default=0)
    asthma = models.IntegerField(default=0)
    dialysis = models.IntegerField(default=0)