# Generated by Django 2.1.3 on 2018-11-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('hurl', models.CharField(default='', max_length=200)),
                ('lat', models.FloatField(default=0)),
                ('lon', models.FloatField(default=0)),
                ('highblood', models.IntegerField(default=0)),
                ('lungCa', models.IntegerField(default=0)),
                ('stomachCa', models.IntegerField(default=0)),
                ('liverCa', models.IntegerField(default=0)),
                ('bowelCa', models.IntegerField(default=0)),
                ('breastCa', models.IntegerField(default=0)),
                ('cesarean', models.IntegerField(default=0)),
                ('antibiotics', models.IntegerField(default=0)),
                ('injection', models.IntegerField(default=0)),
                ('diabetes', models.IntegerField(default=0)),
                ('asthma', models.IntegerField(default=0)),
                ('dialysis', models.IntegerField(default=0)),
            ],
        ),
    ]
