# Generated by Django 2.1.3 on 2018-11-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0002_gradeinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maininfo',
            name='addr',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='etel',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='info',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='tel',
            field=models.CharField(default='', max_length=70),
        ),
    ]
