# Generated by Django 2.1.3 on 2018-11-12 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0005_auto_20181112_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradeinfo',
            name='name',
        ),
    ]
