# Generated by Django 2.1.3 on 2018-11-13 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0006_remove_gradeinfo_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency', models.CharField(default='', max_length=4)),
                ('limbs', models.CharField(default='', max_length=4)),
                ('pregnent', models.CharField(default='', max_length=4)),
                ('newborn', models.CharField(default='', max_length=4)),
                ('burn', models.CharField(default='', max_length=4)),
                ('dialysis', models.CharField(default='', max_length=4)),
                ('hpid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infos.MainInfo')),
            ],
        ),
    ]
